stages:
  split:
    cmd: python src/split.py
    deps:
    - data/raw/train
    - src/split.py
    outs:
    - data/raw/validation
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/
    - src/preprocess.py
    params:
    - preprocess.denoise_weight
    outs:
    - data/prepared
