stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw
    - src/preprocess.py
    outs:
    - data/prepared
  train:
    cmd: python src/train.py
    deps:
    - data/prepared/
    - src/train.py
    outs:
    - metrics/
    - models/
